package com.seevrantillan.safespace.entity;

import java.util.List;

import com.fasterxml.jackson.annotation.JsonIgnore;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

@Entity
@Table(name = "user") // Ensure this matches your actual table name if it's different
public class UserEntity {

    // --- Primary Key ---
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int userID;

    // --- Basic User Details ---
    @Column(length = 32)
    private String username;

    @Column(length = 128)
    private String password;

    @Column(length = 128)
    private String email;

    @Column(length = 32)
    private String gender;

    @Column
    private int age;

    @Column(length = 32)
    private String role;

    @Column(length = 32)
    private String privacySettings;

    @Column(length = 32)
    private String userType;

    // --- Bidirectional Relationships (Collections) ---
    // IMPORTANT: Use @JsonIgnore to break the infinite recursion loop 
    // when converting this entity to JSON (e.g., in a GET or POST response).
    
    @JsonIgnore
    @OneToMany(mappedBy = "user")
    private List<ReactionEntity> reactions;

    @JsonIgnore
    @OneToMany(mappedBy = "user")
    private List<CommentEntity> comments;

    @JsonIgnore
    @OneToMany(mappedBy = "user")
    private List<ModuleEntity> modules;

    @JsonIgnore
    @OneToMany(mappedBy = "user")
    private List<PostEntity> posts;


    // --- Constructors ---

    // No-args constructor is required by JPA and Jackson
    public UserEntity() {}

    // All-args constructor for convenience (optional but helpful)
    public UserEntity(int userID, String username, String password, String email, String gender,
                      int age, String role, String privacySettings, String userType) {
        this.userID = userID;
        this.username = username;
        this.password = password;
        this.email = email;
        this.gender = gender;
        this.age = age;
        this.role = role;
        this.privacySettings = privacySettings;
        this.userType = userType;
    }

    // --- Getters and Setters ---

    // Getter for userID (no setter, as it is generated by the DB)
    public int getUserID() {
        return userID;
    }

    // Since userID is auto-generated, we typically don't expose a public setter.
    // If you need to set it for testing or internal use, you can make the setter private.
    // private void setUserID(int userID) {
    //     this.userID = userID;
    // }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getGender() {
        return gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public int getAge() {
        return age;
    }

    public void setAge(int age) {
        this.age = age;
    }

    public String getRole() {
        return role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    public String getPrivacySettings() {
        return privacySettings;
    }

    public void setPrivacySettings(String privacySettings) {
        this.privacySettings = privacySettings;
    }

    public String getUserType() {
        return userType;
    }

    public void setUserType(String userType) {
        this.userType = userType;
    }

    // Getters and setters for the collections (use with caution in services!)
    public List<ReactionEntity> getReactions() {
        return reactions;
    }

    public void setReactions(List<ReactionEntity> reactions) {
        this.reactions = reactions;
    }

    public List<CommentEntity> getComments() {
        return comments;
    }

    public void setComments(List<CommentEntity> comments) {
        this.comments = comments;
    }

    public List<PostEntity> getPosts() {
        return posts;
    }

    public void setPosts(List<PostEntity> posts) {
        this.posts = posts;
    }

    public List<ModuleEntity> getModules() {
        return modules;
    }

    public void setModules(List<ModuleEntity> modules) {
        this.modules = modules;
    }
}